// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fiber_graphql/todo"
)

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string     `json:"id"`
	Text string     `json:"text"`
	Done bool       `json:"done"`
	User *todo.User `json:"user"`
}
